package com.google.security.zynamics.bindiff.enums;

public enum EPlaceholderType {
  MATCHED_ABOVE_INSTRUCTION_COMMENT,
  MATCHED_BEHIND_INSTRUCTION_COMMENT,
  UNMATCHED_ABOVE_INSTRUCTION_COMMENT,
  UNMATCHED_INSTRUCTION,
  UNMATCHED_BEHIND_INSTRUCTION_COMMENT,
  BASICBLOCK_COMMENT;
}
