name: cmake-build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-26.04
        - os: ubuntu-26.04-arm
        - os: macOS-26
        - os: windows-2025
        - os: windows-11-arm
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Checkout BinExport
      uses: actions/checkout@v6
      with:
        repository: google/binexport
        path: build/binexport

   - name: Set up MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ runner.arch == 'ARM64' && 'arm64' || 'x64' }}

    - name: Enable mold linker (Linux)
      if: runner.os == 'Linux'
      uses: rui314/setup-mold@v1

    - name: Install CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~4.4.0"
        ninjaVersion: "~1.13.1"

    - name: Configure CMake
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: |
        cmake "${GITHUB_WORKSPACE}" -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
          "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" \
          "-DBINDIFF_BINEXPORT_DIR=${GITHUB_WORKSPACE}/build/binexport"

    - name: Build
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: cmake --build . --config "${BUILD_TYPE}"

    - name: Test
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: ctest --build-config "${BUILD_TYPE}" --output-on-failure -R '^[A-Z]'

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: BinDiff-${{ matrix.os }}
        path: |
          ${{ github.workspace }}/build/bindiff
          ${{ github.workspace }}/build/ida/bindiff*
          ${{ github.workspace }}/build/tools/bindiff*
